export const competitorRows = [
  {
    product: "Clout Chaser",
    href: "/docs/how-it-works",
    platform: "TikTok, Reels, Shorts; source-led intake",
    discovery: "Reviewed signal timing, fit, saturation, and Opportunity Score",
    handoff: "Hooks, captions, scripts, clip targets, export specs, and source notes",
    language: "English, Spanish, or bilingual package request",
    proof: "Public-safe, source-backed receipt",
    team: "Studio early-access scope; Operations Studio path for business",
    value: "$0 reviewed sample; paid ranges remain early-access candidates",
    isClout: true,
  },
  {
    product: "Augur",
    href: "https://www.goaugur.com/",
    platform: "TikTok, Reels, and Shorts",
    discovery: "Outliers, momentum, shifts, niche monitoring, and AI analysis",
    handoff: "Hook analysis and exports; broader Content Studio is marked soon",
    language: "Multilingual monitoring; bilingual package output not documented",
    proof: "Public provenance receipt not documented",
    team: "Multi-client niches and branded reports; roles and approvals unclear",
    value: "100-credit free trial; Starter $19 early-bird / $29 list; Pro $59 monthly",
    isClout: false,
  },
  {
    product: "Viralshift",
    href: "https://viralshift.ai/",
    platform: "TikTok, Reels, and Shorts",
    discovery: "Daily-refreshed high-performing videos, engagement ranking, and filters",
    handoff: "Hook analysis at Pro; 30–60 second script generation and CSV at Pro+",
    language: "Bilingual output not documented",
    proof: "Public provenance receipt not documented",
    team: "Team seats and branded reports at Enterprise",
    value: "Free browsing; Pro $49 monthly; Pro+ $99 monthly",
    isClout: false,
  },
  {
    product: "vidIQ",
    href: "https://vidiq.com/plans/",
    platform: "Primarily YouTube",
    discovery: "Niche trends, data-backed ideas, trend research, and optimization",
    handoff: "AI ideation and up to 11 hours of clipping/generation on Max",
    language: "Bilingual package output not documented",
    proof: "Public provenance receipt not documented",
    team: "Roles, permissions, and cross-channel reporting at Enterprise",
    value: "Free tier; Max $39 monthly when billed yearly",
    isClout: false,
  },
  {
    product: "1of10",
    href: "https://1of10.com/pricing",
    platform: "YouTube",
    discovery: "Outlier search, virality monitoring, trending formats, and niche exploration",
    handoff: "AI titles, ideas, thumbnails, and optimization at Pro",
    language: "Bilingual generated output not documented",
    proof: "Public provenance receipt not documented",
    team: "Additional members at Pro; Enterprise onboarding and team access",
    value: "Free tier; Basic $29 and Pro $69 monthly equivalents, billed annually",
    isClout: false,
  },
] as const;

export const competitorReview = {
  checkedAt: "July 16, 2026",
  note: "Competitor features and prices reflect vendor-published pages. Plans can change. ‘Not documented’ means the reviewed public page did not confirm the capability; it does not prove the capability is unavailable.",
} as const;
